# Preprocessing

In [1]:
# Imports
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.metrics import silhouette_score
import seaborn as sns

In [2]:
pre = False

In [3]:
if pre:
    link = "data/2021_Alumnos_pre_normalizadas_angela.xlsx"
else:
    link = "data/2021_Alumnos_post_normalizadas_angela.xlsx"
data = pd.read_excel(link)
data.head()

,Curso,Nivel,Codigo,Edad,Genero,Decision,Otros_campus,Ingenieria_antes,Valoracion_ingenierias,Dedicacion,...,Interes_asignaturas,Salida_profesional,Actividades_instituto,Dificultad_asignaturas,Trabajo,Respeto_cientificos,Efecto_vidas,No_gustar,Examenes,Decisiones_personales
0,AUTOMATIZACION,SENIOR,108472.0,13,Chico,Yo,No,No sé,Buena,NaN,...,3.0,3.0,3.0,1.0,3.0,2.0,4.0,2.0,1.0,4.0
1,AUTOMATIZACION,SENIOR,1107000.2,16,Chico,Mis padres,No,No sé,Me da igual,no se,...,3.0,1.0,3.0,5.0,1.0,4.0,5.0,3.0,5.0,3.0
2,AUTOMATIZACION,SENIOR,1107156.0,16,Chico,Yo,"2016, 2018, 2019",Sí,Muy buena,informatica,...,5.0,5.0,5.0,1.0,5.0,4.0,4.0,1.0,2.0,4.0
3,AUTOMATIZACION,SENIOR,1808307.0,13,Chico,"Yo, Mis padres","2016, 2017, 2018, 2019, 2020 (online)",No sé,Muy buena,"Psicología, investigar cómo pensamos los humanos.",...,5.0,4.0,4.0,4.0,4.0,3.0,5.0,1.0,3.0,5.0
4,AUTOMATIZACION,SENIOR,2609571.0,16,Chico,Mis amigos,No,No sé,Buena,Ingenieria,...,4.0,3.0,5.0,4.0,4.0,4.0,5.0,4.0,3.0,4.0

In [4]:
data = data.drop_duplicates(subset = 'Codigo')

In [5]:
data.count()

Curso                                     278
Nivel                                     278
Codigo                                    278
Edad                                      278
Genero                                    278
Decision                                  278
Otros_campus                              278
Ingenieria_antes                          278
Valoracion_ingenierias                    278
Dedicacion                                 78
Trabajo_padre                             278
Trabajo_madre                             278
Posicion_clase                            278
Tipo_estudiante                           278
Adaptacion                                277
Puntuacion_profesor                       277
Puntuacion_apoyo                          277
Laboratorios_escuela                      277
Laboratorios_comunicaciones               277
Sensibilizacion_ONG                       251
Material                                  277
Ingenieria_despues                        277
x_AQu_TeGustar_aDedicarteEnElFuturo__1    277
TuValoraci_nSobreLaIngenier_aEs__1        277
Nivel_matematicas                         277
x_AQu_TeGustar_aDedicarteEnElFuturo__2    159
Recomendacion                             277
Repetir                                   277
Puntuacion_curso                          277
Mejor_curso                               277
Peor_curso                                277
Mejorar                                   253
Gustar                                    277
Estudiar                                  277
Entender                                  277
No_entender                               277
Profesional                               277
Actividades                               277
Carrera                                   277
Facilidad                                 277
Disfrutar                                 277
No_trabajo                                277
Mundo_mejor                               277
Interes_asignaturas                       277
Salida_profesional                        277
Actividades_instituto                     277
Dificultad_asignaturas                    277
Trabajo                                   277
Respeto_cientificos                       277
Efecto_vidas                              277
No_gustar                                 277
Examenes                                  277
Decisiones_personales                     277
dtype: int64

In [6]:
data.columns

Index(['Curso', 'Nivel', 'Codigo', 'Edad', 'Genero', 'Decision',
       'Otros_campus', 'Ingenieria_antes', 'Valoracion_ingenierias',
       'Dedicacion', 'Trabajo_padre', 'Trabajo_madre', 'Posicion_clase',
       'Tipo_estudiante', 'Adaptacion', 'Puntuacion_profesor',
       'Puntuacion_apoyo', 'Laboratorios_escuela',
       'Laboratorios_comunicaciones', 'Sensibilizacion_ONG', 'Material',
       'Ingenieria_despues', 'x_AQu_TeGustar_aDedicarteEnElFuturo__1',
       'TuValoraci_nSobreLaIngenier_aEs__1', 'Nivel_matematicas',
       'x_AQu_TeGustar_aDedicarteEnElFuturo__2', 'Recomendacion', 'Repetir',
       'Puntuacion_curso', 'Mejor_curso', 'Peor_curso', 'Mejorar', 'Gustar',
       'Estudiar', 'Entender', 'No_entender', 'Profesional', 'Actividades',
       'Carrera', 'Facilidad', 'Disfrutar', 'No_trabajo', 'Mundo_mejor',
       'Interes_asignaturas', 'Salida_profesional', 'Actividades_instituto',
       'Dificultad_asignaturas', 'Trabajo', 'Respeto_cientificos',
       'Efecto_vidas', 'No_gustar', 'Examenes', 'Decisiones_personales'],
      dtype='object')

## Calculate Dimensions

### Fix Negative variables

In [7]:
data.No_gustar = 6 - data.No_gustar
data.Profesional = 6 - data.Profesional
data.No_trabajo = 6 - data.No_trabajo
data.No_entender = 6- data.No_entender
data.Dificultad_asignaturas = 6 - data.Dificultad_asignaturas
data.Examenes = 6 - data.Examenes

In [8]:
data["Gusto"] = data[["Gustar", "Actividades", "Disfrutar", "Interes_asignaturas", "Actividades_instituto", "No_gustar"]].mean(axis=1)
data["Interes_profesional"] = data[["Estudiar", "Profesional", "Carrera", "No_trabajo", "Salida_profesional", "Trabajo"]].mean(axis = 1)
data["Autoeficacia"] = data[["No_entender", "Facilidad", "Dificultad_asignaturas", "Examenes"]].mean(axis = 1)
data["Utilidad"] = data[["Entender", "Mundo_mejor", "Respeto_cientificos", "Efecto_vidas", "Decisiones_personales"]].mean(axis = 1)

In [9]:
data.describe()

,Codigo,Edad,Puntuacion_profesor,Puntuacion_apoyo,Puntuacion_curso,Gustar,Estudiar,Entender,No_entender,Profesional,...,Trabajo,Respeto_cientificos,Efecto_vidas,No_gustar,Examenes,Decisiones_personales,Gusto,Interes_profesional,Autoeficacia,Utilidad
count,2.780000e+02,278.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,...,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000,277.000000
mean,5.915697e+07,13.309353,9.458484,9.036101,9.245487,4.371841,4.234657,4.577617,4.314079,3.794224,...,3.696751,4.025271,4.361011,4.454874,3.310469,4.263538,4.210590,3.915764,3.701264,4.366787
std,6.302603e+08,2.195660,0.861353,2.008712,0.987800,0.822466,0.955054,0.635830,0.984803,1.223666,...,1.114020,0.898515,0.789191,0.990326,1.315046,0.880056,0.716001,0.849910,0.797623,0.562907
min,0.000000e+00,9.000000,2.000000,1.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.166667,1.000000,1.750000,1.200000
25%,8.325000e+05,11.000000,9.000000,9.000000,9.000000,4.000000,4.000000,4.000000,4.000000,3.000000,...,3.000000,3.000000,4.000000,4.000000,2.000000,4.000000,3.833333,3.333333,3.000000,4.000000
50%,1.701976e+06,13.000000,10.000000,10.000000,10.000000,5.000000,5.000000,5.000000,5.000000,4.000000,...,4.000000,4.000000,5.000000,5.000000,3.000000,4.000000,4.333333,4.000000,3.750000,4.400000
75%,2.312596e+06,15.000000,10.000000,10.000000,10.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,4.000000,5.000000,4.833333,4.666667,4.250000,4.800000
max,7.720214e+09,17.000000,10.000000,10.000000,10.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

## Reduce Dataset

In [10]:
if pre:
    data_red = data[['Codigo', 'Edad', 'Nivel', 'Genero', 'Gusto', 'Interes_profesional', 'Autoeficacia', 'Utilidad']]
else:
    data_red = data[['Codigo', 'Edad', 'Nivel', 'Genero', 'Gusto', 'Interes_profesional', 'Autoeficacia', 'Utilidad']]
data_red

,Codigo,Edad,Nivel,Genero,Gusto,Interes_profesional,Autoeficacia,Utilidad
0,108472.0,13,SENIOR,Chico,3.333333,3.166667,4.50,3.8
1,1107000.2,16,SENIOR,Chico,3.666667,3.000000,2.50,4.0
2,1107156.0,16,SENIOR,Chico,4.666667,5.000000,4.50,4.2
3,1808307.0,13,SENIOR,Chico,4.333333,3.666667,3.50,4.6
4,2609571.0,16,SENIOR,Chico,3.833333,3.000000,2.75,3.8
...,...,...,...,...,...,...,...,...
278,1307385.0,14,SENIOR,Chico,3.000000,3.000000,3.00,3.0
279,2101024.0,15,SENIOR,Chica,4.166667,4.166667,4.50,4.4
280,2703000.0,13,SENIOR,Chico,3.666667,3.166667,4.00,4.0
281,2908377.0,13,SENIOR,Chico,3.166667,2.166667,3.75,3.6
282,3008623.0,15,SENIOR,Chica,4.666667,4.333333,3.25,4.8

In [11]:
if pre:
    data_red.to_csv("data/2021_Alumnos_pre_red_angela.csv", index = False)
else:
    data_red.to_csv("data/2021_Alumnos_post_red_angela.csv", index = False)